POST https://node-do-zero-5yuv.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-do-zero-5yuv.onrender.com/videos


###

PUT https://node-do-zero-5yuv.onrender.com/videos/d664d91b-37b0-4df4-a6ea-44f24590a5f0	   
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o quarto video",
    "duration": 100
}

###

DELETE https://node-do-zero-5yuv.onrender.com/videos/20bed124-29d8-473c-8a13-322190a42d76   